# Generated by Django 4.1.2 on 2022-10-17 20:25

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', api.models.CapitalizeCharField(max_length=31, unique=True, verbose_name='Color')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', api.models.CapitalizeCharField(max_length=255, unique=True, verbose_name='Mark')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', api.models.CapitalizeCharField(max_length=255, unique=True, verbose_name='Model')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.color')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.mark')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.model')),
            ],
        ),
    ]
